baseurl = "https://www.oddsocado.github.io/" # Make sure to end baseurl with a '/'
title = "Oddsocado"
# Shown in the side menu
copyright = "&copy; 2021. All rights reserved."
canonifyurls = true
paginate = 10

[indexes]
  tag = "tags"
  topic = "topics"

[params]
  subtitle = "making tacos better"
  googleAnalytics = "G-3LY6QV1HFH"
  highlightjs = "androidstudio"
  highlightjs_extra_languages = ["yaml"]
  dateFormat = "02 Jan 2006, 15:04"


[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 1
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "Posts"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 2
    identifier = "post"
    url = "/post/"
  [[menu.main]]
    name = "Reference"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 3
    identifier = "ref"
    url = "/ref/"
  [[menu.main]]
    name = "About"
    pre = "<i class='fa fa-user fa-fw'></i>"
    weight = 4
    identifier = "about"
    url = "/about/"

[social]
  # Link your social networking accounts to the side menu
  # by entering your username or ID.

  # SNS microblogging
  twitter = "oddsocado"
  reddit = "oddsocado"
